name: Docker Image

on:
  push:
  dispatch_workflow: 

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check pyton2 installed
        run: python2 --version && echo "Python2 installed" || echo "Python2 not installed"

  ubuntu-container:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check pyton2 installed
        run: python2 --version && echo "Python2 installed" || echo "Python2 not installed"
    