name: Docker Image

on:
  push:
  workflow_dispatch: 

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check pyton2 installed
        run: python2 --version && echo "Python2 installed" || echo "Python2 not installed"

      - name: Run install_tool.sh
        run: ./install_tool.sh

  ubuntu-container-exiting:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check pyton2 installed
        run: python2 --version && echo "Python2 installed" || echo "Python2 not installed"
 
      - name: Install Python3
        run: |
          apt-get update && \
          apt-get install python3 python3-pip -y && \
          python3 --version

      - name: Run install_tool.sh
        run: ./install_tool.sh

  # Verify the fix
  ubuntu-container-fix:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check pyton2 installed
        run: python2 --version && echo "Python2 installed" || echo "Python2 not installed"

      - name: Install Python3
        run: |
          apt-get update && \
          apt-get install python3 python3-pip -y && \
          python3 --version

      - name: Run install_tool_fix.sh
        run: ./install_tool_fix.sh
          
  ubuntu-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check pyton2 installed
        run: python2 --version && echo "Python2 installed" || echo "Python2 not installed"

      # Verify backward compatibility with the fix.
      - name: Run install_tool_fix.sh
        run: ./install_tool_fix.sh      
        